# Generated by Django 4.1 on 2021-11-01 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=6)),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=9)),
                ("currency", models.CharField(max_length=3)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historic_values",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
    ]
