# Generated by Django 4.1 on 2021-11-06 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='The exchange symbol that this item is traded under.', max_length=6)),
                ('name', models.TextField()),
                ('sector', models.CharField(choices=[('EN', 'energy'), ('MA', 'materials'), ('IN', 'industrials'), ('UT', 'utilities'), ('HE', 'healthcare'), ('FI', 'financials'), ('CD', 'consumer_discretionary'), ('CS', 'consumer_staples'), ('IT', 'information_technology'), ('CS', 'communication_services'), ('RE', 'real_estate')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('currency', models.CharField(max_length=3)),
                ('after_hours', models.DecimalField(decimal_places=3, help_text='The close price of the ticker symbol in after hours trading.', max_digits=9)),
                ('close', models.DecimalField(decimal_places=3, help_text='The close price for the symbol in the given time period.', max_digits=9)),
                ('high', models.DecimalField(decimal_places=3, help_text='The highest price for the symbol in the given time period.', max_digits=9)),
                ('low', models.DecimalField(decimal_places=3, help_text='The lowest price for the symbol in the given time period.', max_digits=9)),
                ('_open', models.DecimalField(decimal_places=3, help_text='The open price for the symbol in the given time period.', max_digits=9)),
                ('pre_market', models.DecimalField(decimal_places=3, help_text='The open price of the ticker symbol in pre-market trading.', max_digits=9)),
                ('volume', models.DecimalField(decimal_places=3, help_text='The trading volume of the symbol in the given time period.', max_digits=19)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historic_values', to='assets.asset')),
            ],
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(models.F('symbol'), name='unique_symbol_asset'),
        ),
        migrations.AddConstraint(
            model_name='historicvalue',
            constraint=models.UniqueConstraint(fields=('asset', 'date_time'), name='unique_asset_date_time_historic_value'),
        ),
    ]
