# Generated by Django 4.1 on 2021-11-06 18:57

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
    ]
