# Generated by Django 4.1 on 2021-11-01 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolios", "0001_initial"),
        ("users", "0001_initial"),
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portfolios",
                to="users.customuser",
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="investments",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="investments",
                to="portfolios.portfolio",
            ),
        ),
    ]
